### PR TITLE
Fast exponentiation

### PR DESCRIPTION
**Pull request by AurumnPegasus**
Fast exponentiation is an easy and heavily used algorithm to find the exponent of a given base in minimal time (time complexity is O(logK)). It is often also used in cases where we need to calculate powers in terms of 10^18 and such, in which cases taking the mod is expected. In my program i have not done so, but if required we just need to add modulo according to modular arithmetic and it can be easily done

Climbing stairs is a fairly common beginner problem which uses the principle of recurssion. By using dynamic programming and memorization i this i have reduced the time complexity drastically when multiple test cases are involved.

### CODE REVIEW

**Comment by darpanjbora** [comment]
Kindly add the file fast_exponentiation to a specific folder. Thanks.

**Comment by AurumnPegasus** [comment]
Done

**Comment by darpanjbora** [comment]
Thank you for your contribution. Keep contributing. :)

**Comment by darpanjbora** [comment]
@all-contributors please add @AurumnPegasus  for code

**Pull request merged**
