### PR TITLE
I added new Program on Math Folder

### PR DESCRIPTION
**Pull request by risingstar-bit**
I added a program to find the square root of a number using formula of NEWTON RAPHSON.

### CODE REVIEW

**Comment by risingstar-bit** [comment]
@darpanjbora please review it

**Review by Alok-Satyam — APPROVED** [review]

**Review by Alok-Satyam — APPROVED** [review]

**Review by Alok-Satyam — CHANGES_REQUESTED** [review]
nice

**Review by darpanjbora — APPROVED** [review]
LGTM!

**Comment by risingstar-bit** [comment]
@darpanjbora sir please add label hacktoberfest-accepted🙏

**Pull request merged**
